spring:
  application:
    name: telegram-nezha-bot
  threads:
    virtual:
      enabled: true

telegram:
  bot:
    config:
      token:
      userName:
  proxy:
    config:
      address: 127.0.0.1
      port: 10808
      proxyType: SOCKS5


nezha:
  address: https://status.imtop1.moe

  path:
    serverInfo: /api/v1/server/list
    serverDetail: /api/v1/server/details
