spring:
  application:
    name: telegram-nezha-bot

telegram:
  bot:
    config:
      token:
      userName:
  proxy:
    config:
      address: 127.0.0.1
      port: 10808
      proxyType: NO_PROXY


nezha:
  address:
  token:
  path:
    serverInfo: /api/v1/server/list
    serverDetail: /api/v1/server/details
